"""LPT v2 共享默认值与项目路径。"""

from __future__ import annotations

from pathlib import Path


PROJECT_ROOT = Path(__file__).resolve().parents[1]
TOKENIZER_PATH = PROJECT_ROOT / "lpt_model" / "ds_tokenizer"
ARTIFACT_ROOT_DIR = PROJECT_ROOT / "artifacts" / "lpt_v2"

MODEL_ABBR = "LPTv2"
MODEL_NAME_EN = "Ling Pre-trained Transformer v2"
MODEL_NAME_ZH = "灵预 v2"
CHAT_TEMPLATE_VERSION = "lpt-ds-v1"

LPT_V2_DEV_TINY_PRESET = "lpt_v2_dev_tiny"
LPT_V2_SMALL_PRESET = "lpt_v2_small"
LPT_V2_SMALL_BASE_PRESET = "lpt_v2_small_base"
LPT_V2_BASE_PRESET = "lpt_v2_base"
LPT_V2_LARGE_PRESET = "lpt_v2_large"
DEFAULT_MODEL_SIZE_PRESET = LPT_V2_SMALL_BASE_PRESET

LPT_V2_BOOTSTRAP_PROFILE = "lpt_v2_bootstrap"
LPT_V2_SDPA_LOCAL_PROFILE = "lpt_v2_sdpa_local"
LPT_V2_PAGED_KV_PROFILE = "lpt_v2_paged_kv"
LPT_V2_ASSIST_PROFILE = "lpt_v2_assist"
LPT_V2_BASE_PROFILE = "lpt_v2_base"
LPT_V2_MEMORY_PROFILE = "lpt_v2_memory"
DEFAULT_PROFILE = LPT_V2_ASSIST_PROFILE
LPT_V2_BASELINE_PROFILES = (
    LPT_V2_BOOTSTRAP_PROFILE,
    LPT_V2_SDPA_LOCAL_PROFILE,
    LPT_V2_PAGED_KV_PROFILE,
    LPT_V2_ASSIST_PROFILE,
    LPT_V2_BASE_PROFILE,
    LPT_V2_MEMORY_PROFILE,
)

DEFAULT_DEVICE = "auto"
DEFAULT_DTYPE = "auto"
DEFAULT_TRAINING_STAGE = "train"
DEFAULT_TRAINING_BATCH_SIZE = 1
DEFAULT_TRAINING_EPOCHS = 1
DEFAULT_TRAINING_MAX_STEPS = None
DEFAULT_TRAINING_LEARNING_RATE = 1e-4
DEFAULT_WEIGHT_DECAY = 0.1
DEFAULT_GRADIENT_ACCUMULATION_STEPS = 1
DEFAULT_MAX_GRAD_NORM = 1.0
DEFAULT_WARMUP_RATIO = 0.03
DEFAULT_TRAINING_SEED = 20260503
DEFAULT_DETERMINISTIC_ALGORITHMS = True
DEFAULT_SEQUENCE_PACKING_ENABLED = True
DEFAULT_LOG_INTERVAL_STEPS = 10
DEFAULT_EVAL_INTERVAL_STEPS = 0
DEFAULT_EVAL_MAX_BATCHES = None
DEFAULT_SAVE_INTERVAL_STEPS = 0
DEFAULT_LATEST_SAVE_INTERVAL_STEPS = 10
DEFAULT_SAVE_OPTIMIZER = True
DEFAULT_SAVE_SCHEDULER = True
DEFAULT_SAVE_BEST_CHECKPOINT = False
DEFAULT_BEST_CHECKPOINT_METRIC = "loss"
DEFAULT_BEST_CHECKPOINT_MIN_DELTA = 0.0
DEFAULT_TENSORBOARD_ENABLED = True

TEXT_PRETRAIN_MANIFEST_PATH = Path("data/manifests/text_pretrain.json")
CHAT_SFT_MANIFEST_PATH = Path("data/manifests/chat_sft.json")
CHAT_LORA_MANIFEST_PATH = Path("data/manifests/chat_lora.json")
TEXT_PRETRAIN_ARTIFACT_DIR = ARTIFACT_ROOT_DIR / "text_pretrain"
CHAT_SFT_ARTIFACT_DIR = ARTIFACT_ROOT_DIR / "chat_sft"
CHAT_LORA_ARTIFACT_DIR = ARTIFACT_ROOT_DIR / "chat_lora"

TEXT_PRETRAIN_BATCH_SIZE = 2
TEXT_PRETRAIN_EPOCHS = 1
TEXT_PRETRAIN_LEARNING_RATE = 3e-4
TEXT_PRETRAIN_WARMUP_RATIO = 0.1

CHAT_SFT_BATCH_SIZE = 1
CHAT_SFT_EPOCHS = 1
CHAT_SFT_LEARNING_RATE = 3e-4
CHAT_SFT_WARMUP_RATIO = 0.1

CHAT_LORA_BATCH_SIZE = 10
CHAT_LORA_EPOCHS = 1
CHAT_LORA_LEARNING_RATE = 6e-4
CHAT_LORA_WARMUP_RATIO = 0.1
DEFAULT_LORA_BASE_SOURCE = "text_pretrain"
VALID_LORA_BASE_SOURCES = ("text_pretrain", "chat_sft")
DEFAULT_LORA_RANK = 8
DEFAULT_LORA_ALPHA = 16.0
DEFAULT_LORA_DROPOUT = 0.05
DEFAULT_LORA_TARGET_MODULES = ("q_proj", "k_proj", "v_proj", "o_proj")

DEFAULT_GENERATION_DO_SAMPLE = True
DEFAULT_GENERATION_TEMPERATURE = 0.7
DEFAULT_GENERATION_TOP_K = 50
DEFAULT_GENERATION_TOP_P = 0.9
DEFAULT_GENERATION_MAX_LENGTH = 200
DEFAULT_GENERATION_REPETITION_PENALTY = 1.1
DEFAULT_GENERATION_REPETITION_WINDOW_SIZE = 256

DEFAULT_EVAL_VOCAB_SIZE = 128
DEFAULT_EVAL_BATCH_SIZE = 1
DEFAULT_EVAL_SEQUENCE_LENGTH = 16
DEFAULT_EVAL_DECODE_STEPS = 1
DEFAULT_RESOURCE_DECODE_STEPS = 4
DEFAULT_MEMORY_EVAL_SEQUENCE_LENGTH = 8
DEFAULT_LONG_CONTEXT_ATTENTION_WINDOW_SIZE = 8
DEFAULT_INFERENCE_PROMPT_IDS = "1,2,3"
DEFAULT_INFERENCE_MAX_NEW_TOKENS = 8
DEFAULT_CHAT_MODEL_SOURCE = "chat_sft"
